# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blueprint < Formula
  desc "Blueprint SDLC — Turn Claude Code into a disciplined engineering team"
  homepage "https://github.com/skaisser/blueprint"
  version "2.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skaisser/blueprint/releases/download/v2.0.1/blueprint-darwin-amd64.tar.gz"
      sha256 "48ebef8af7fef4a5e5d3d738a2f38c7ec8c928149fd4bb02f8ec6b4b73f6e2ef"

      define_method(:install) do
        bin.install "blueprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skaisser/blueprint/releases/download/v2.0.1/blueprint-darwin-arm64.tar.gz"
      sha256 "6792854c728f2fcde9c45c86583252281d4ed4832c6a92f902ab7f76a7614a1a"

      define_method(:install) do
        bin.install "blueprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaisser/blueprint/releases/download/v2.0.1/blueprint-linux-amd64.tar.gz"
      sha256 "470f2a2a72543c90e2543acafe67bf77a7fd1efd9dc7d6cab238e84149a1f03c"
      define_method(:install) do
        bin.install "blueprint"
      end
    end
  end

  test do
    system "#{bin}/blueprint", "version"
  end
end
